### ISSUE TITLE
 yaml: unknown anchor 'cc_install_buildpacks' referenced

### ISSUE THREAD

**Issue by roninby** [cloudfoundry/cf-deployment#182]
Hello,

I'd like to test cf on a vsphere cluster using cf-deployment. The deploy failed at the very beginning as below:

```
[gcps@ansiblehost cf-deployment]$ bosh2 -e bosh-1 -d cf-1 deploy cf-1/cf-deployment.cf-1.yml \
> -o operations/scale-to-one-az.yml \
> --vars-store cf-1/deployment-vars.yml \
> -v system_domain=cf.gcps.lab
Using environment '10.10.0.6' as client 'admin'

Using deployment 'cf-1'

Evaluating manifest:
  yaml: unknown anchor 'cc_install_buildpacks' referenced

Exit code 1
```

I guess there're some misconfiguration in my cf-deployment.yml in connection with special characters "&" and "*",  but I cannot figure out how to fix it. Is there any documentation about it? Or is there any sample cf-deployment.yml for vsphere environment?

From cf-deployment.yml:
```
        install_buildpacks: &cc_install_buildpacks
        - name: binary_buildpack
          package: binary-buildpack
        - name: dotnet_core_buildpack
          package: dotnet-core-buildpack

       ...
       ...

      cc:
        db_encryption_key: "((cc_db_encryption_key))"
        default_to_diego_backend: true
        install_buildpacks: *cc_install_buildpacks
        default_running_security_groups: *cc_default_running_security_groups
        default_staging_security_groups: *cc_default_staging_security_groups
        security_group_definitions: *cc_security_group_definitions

```

Thanks in advance.
