### ISSUE TITLE
insecure_docker_registry_list

### ISSUE THREAD

**Issue by deltatree** [cloudfoundry/cf-deployment#183]
where I have to set insecure_docker_registry_list?
Please make an example and add it to the documentation.

**Comment by dsabeti** [comment]
Hi @deltatree. It depends on whether you're including the [`bypass-cc-bridge.yml`](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/bypass-cc-bridge.yml) ops file.

If you are not using that ops-file, then you'll need to write an ops-file to add `insecure_docker_registry_list` to the [appropriate path on the stager job](https://github.com/cloudfoundry/capi-release/blob/develop/jobs/stager/spec#L83). It would be something like this:
```
- type: replace
  path: /instance_groups/name=cc-bridge/jobs/name=stager/properties/capi/stager/insecure_docker_registry_list?
  value:
  - REGISTRY_1
  - REGISTRY_2
  ...
```

If you _are_ using the `bypass-cc-bridge.yml` ops-file, then you'll need to add it to [the cloud controller job instead](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/bosh/jobs/cloud_controller_ng/spec#L837):
```
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego/insecure_docker_registry_list?
  value:
  - REGISTRY_1
  - REGISTRY_2
  ...
```

As for documenting this, we're trying to figure out the best way to expose all of the things that deployers can configure in their deployments. There are literally hundreds of possible configuration parameters, so giving an example for each one seems unlikely. I'd really like to build a table that deployers can reference, with links to the teams that support those features (in this case, it would be the CAPI team).
