### ISSUE TITLE
memory and disk overcommit properties  

### ISSUE THREAD

**Issue by prashantgnet** [cloudfoundry/cf-deployment#274]
How to define "memory overcommit" and "disk overcommit" properties for "cf-deployment"? what is the default values for it?

**Comment by dsabeti** [comment]
@prashantgnet 
In cf-deployment, we try to use defaults defined by releases wherever you can. However, even though the properties don't appear in the manifest explicitly any longer (since we're using the default values), you can always introduce them via ops-file. 

For example, if you want to set `diego.executor.memory_capacity_mb`, you can write an ops-file like this:
```
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/executor?/memory_capacity_mb
  value: XYZ
```
The `?` in the middle of the path orders the BOSH CLI to add that property (and all sub-properties to the right) to the manifest. The result you'd see from applying this ops-file would look something like this:
```
...
- name: rep
  release: diego
  properties:
    diego:
      rep:
        ...
    executor:
      memory_capacity_mb: XYZ
```

Whichever properties you were setting in your manifest before cf-deployment, you can always add with an ops-file.
