### ISSUE TITLE
Remove last vestiges of etcd?

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/cf-deployment#316]
```yaml
  - name: bbs
    release: diego
    properties:
      diego:
          etcd:
            machines: []
            ca_cert: nil
            client_cert: nil
            client_key: nil
```

[from here](https://github.com/cloudfoundry/cf-deployment/blob/1f89d70106541528b2f0d0d5bc50f3b851d8b49b/cf-deployment.yml#L283-L287)
