### ISSUE TITLE
wildcard is not allowed under application manifest for routes section

### ISSUE THREAD

**Issue by prashantgnet** [cloudfoundry/cf-deployment#399]
As domain and host are going to be deprecated, I am trying to use routes property for application manifest for "*" i.e. wildcard host-name to support multi-tenancy but it gives me following error message

```
cf push -f manifest.yml
Pushing from manifest to org o / space o93 as admin...
Using manifest file manifest.yml
The route '*.o93r2.testdoamin.com/tenant' is not a properly formed URL
FAILED 
```

Following is my application manifest file, I have tried multiple options like defining http, www, double quotes but no luck

```
---
applications:
- name: test-tenant
  memory: 2048M
  disk_quota: 1024M
  instances: 1
  timeout: 300
  health-check-type: http
  health-check-http-endpoint: /tenant/commons/health
  path: ./jars/tenant-service.jar
  buildpack: java_buildpack
  routes:
  - route: '*.o93r2.testdomain.com/tenant'
  - route: '*.os93r2.testdomain.com/tenant'
  env:
```

**Comment by XenoPhex** [comment]
Looks like the way the CLI is parsing the route in the YAML file is incorrect. For now, a work around is to create and map the routes by hand (via the `cf map-route`) command. We'll try and get the fix in shortly!

**Comment by XenoPhex** [comment]
Fixed in the following Tracker story: https://www.pivotaltracker.com/story/show/155060885

**Comment by prashantgnet** [comment]
Thanks for quickly fixing the issue, I would like to know which CLI version will contains this fix?

Thanks,
Prashant

**Comment by jbpivotal** [comment]
@prashantgnet This fix will be in cf CLI v6.35.0, which is the next release and almost ready to ship.

**Comment by prashantgnet** [comment]
I know my queries are not related to mentioned issue but I don't want to raise new issue.

1. When domain and host are going to be deprecated and replace by route property?
2.  Is the removal of domain and host just from the cf CLI or is it a change in the cloud controller itself?

Thanks,
Prashant

**Comment by prashantgnet** [comment]
Verified and working fine using CF CLI 6.35

Thanks,
Prashant

**Comment by jbpivotal** [comment]
@prashantgnet Thanks for confirming.

**Comment by dsabeti** [comment]
Great!, I'll go ahead and close this issue, but feel free to re-open if you need more help.

**Comment by hoegaarden** [comment]
We still see the same issue with `cf version 7.2.0+be4a5ce2b.2020-12-10`.

We've
- pushed an app manually
- manually bound wildcard routes to the app
- and then used `cf create-app-manifest` to get the manifest

Applying that manifest then resulted in an error, so we need to do the route mapping out of band for now.

```yaml
---
applications:
- name: error-page
  stack: cflinuxfs3
  routes:
  - route: "*.apps.dev.datev.de"
  - route: "*.apps.dev.cf.datev.dvint.cloud"
  - route: "*.apps-internal.dev.datev.de"
  no-route: true
  buildpacks:
  - nginx_buildpack
  processes:
  - type: web
    instances: 3
    memory: 16M
    disk_quota: 100M
    health-check-type: port
```

**Comment by hoegaarden** [comment]
We still see the same issue with `cf version 7.2.0+be4a5ce2b.2020-12-10`.

We've
- pushed an app manually
- manually bound wildcard routes to the app
- and then used `cf create-app-manifest` to get the manifest

Applying that manifest then resulted in an error, so we need to do the route mapping out of band for now.

```yaml
---
applications:
- name: error-page
  stack: cflinuxfs3
  routes:
  - route: "*.apps.XXX.com"
  - route: "*.apps.domain2.XXX.com"
  - route: "*.apps.domain1.XXX.com"
  no-route: true
  buildpacks:
  - nginx_buildpack
  processes:
  - type: web
    instances: 3
    memory: 16M
    disk_quota: 100M
    health-check-type: port
```
