### ISSUE TITLE
ops-file to change reverse_log_proxy and traffic_controller co-location

### ISSUE THREAD

**Issue by holgero** [cloudfoundry/cf-deployment#406]
Reverse log proxy and traffic controller have different tasks and there exist different formulas for how they should be scaled. Unfortunately they are co-located in default manifest.

I started the discussion about this in https://github.com/cloudfoundry/loggregator/issues/25. In that issue on the loggregator project I got the answer `The default co-location is to help keep your VM count down in small deployments. For larger deployments, you can use an ops-file to deploy traffic-controller and RLP to different instance groups.` from @thepeterstone.

I offered to create such an ops-file and to contribute it here in `cf-deployment`. While writing this ops-file I realized that it will be impossible to do it "right": Many ops-files manipulate the set of "known" instance-groups. If I add a new instance-group to split log-api, there is no way to make this compatible with these ops-files.

So I am stepping back from that attempt a bit and ask here first: 
* How can this be done without invalidating the existing ops-files?
* Is an ops-file for this the right approach?
* Is it needed to support migration from the state where RLP and traffic controller are co-located to separate jobs?
* Is the idea that `cf-deployment` is meant for a small deployment correct? Or should it be the default for large deployment, and scaling it down is the optional operation?

**Comment by holgero** [comment]
Here is what I have got so far:
```yml
---
- type: remove
  path: /instance_groups/name=log-api/jobs/name=consul_agent/properties/consul/agent/services/reverse_log_proxy

- type: remove
  path: /instance_groups/name=log-api/jobs/name=reverse_log_proxy

- type: replace
  path: /instance_groups/name=log-api:after
  value:
    name: reverse_log_proxy
    azs:
    - z1
    - z2
    instances: 2
    vm_type: minimal
    stemcell: default
    update:
      serial: true
    networks:
    - name: default
    jobs:
    - name: consul_agent
      release: consul
      consumes:
        consul_common: {from: consul_common_link}
        consul_server: nil
        consul_client: {from: consul_client_link}
      properties:
        consul:
          agent:
            services:
              reverse_log_proxy: {}
    - name: reverse_log_proxy
      release: loggregator
      provides:
        reverse_log_proxy: {as: reverse_log_proxy, shared: true}
      properties:
        loggregator:
          tls:
            ca_cert: "((loggregator_ca.certificate))"
            reverse_log_proxy:
              cert: "((loggregator_tls_rlp.certificate))"
              key: "((loggregator_tls_rlp.private_key))"
```
