### ISSUE TITLE
Deploy cf-deployment for vsphere 

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/cf-deployment#407]
Hi team:
    I deploy cf-deployment for vsphere , i upload cloud config for there:
   ```
  ---
azs:
- name: z1
  cloud_properties:
    datacenters:
    - clusters:
      - cluster1

networks:
- name: default
  subnets:
  - az: z1
    gateway: 192.168.6.254
    dns: [192.168.1.1]
    range: 192.168.6.0/24
    reserved: 
      - 192.168.6.1
      - 192.168.6.2
      - 192.168.6.3
      - 192.168.6.4
      - 192.168.6.5
      - 192.168.6.6
      - 192.168.6.7
      - 192.168.6.8
      - 192.168.6.9
      - 192.168.6.10
      - 192.168.6.11
      - 192.168.6.12
      - 192.168.6.13
      - 192.168.6.14
      - 192.168.6.15
      - 192.168.6.16
      - 192.168.6.17
      - 192.168.6.18
      - 192.168.6.19
      - 192.168.6.20
      - 192.168.6.254
      - 192.168.6.255
    cloud_properties:
      name: cf1

vm_types:
- name: minimal
  cloud_properties:
    cpu: 1
    ram: 4096
    disk: 10240
- name: small
  cloud_properties:
    cpu: 2
    ram: 8192
    disk: 10240
- name: small-highmem
  cloud_properties:
    cpu: 4
    ram: 32768
    disk: 10240

disk_types:
- disk_size: 5120
  name: 5GB
- disk_size: 10240
  name: 10GB
- disk_size: 100240
  name: 100GB

vm_extensions:
- name: cf-router-network-properties
- name: cf-tcp-router-network-properties
- name: diego-ssh-proxy-network-properties
- name: 50GB_ephemeral_disk
  cloud_properties:
    disk: 51200
- name: 100GB_ephemeral_disk
  cloud_properties:
    disk: 102400

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: small-highmem
  network: default
   ```

but when i deploy ,is show error
![image](https://user-images.githubusercontent.com/21106445/36273047-38bd5c66-12be-11e8-939a-a942efa78380.png)
Can you give a cloud config that deploy successful ?

**Comment by dsabeti** [comment]
Hi @geekyzk. We can't give you a cloud-config, because it will necessarily be specific to your infrastructure setup. Luckily, I can still tell you what's going on here: by default, cf-deployment deploys to three AZs, but you cloud-config only configures a single one (look at the `azs` and `networks` section).

You've got two options:
1. Configure your cloud-config with two more AZs
2. Deploy your CF to a single AZ. You can use [this ops-file in cf-deployment](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/scale-to-one-az.yml).

**Comment by geekyzk** [comment]
@dsabeti Hi,I using one az,but when deploy 
![image](https://user-images.githubusercontent.com/21106445/36274209-fb02ddde-12c1-11e8-9619-2f83145db75a.png)

**Comment by geekyzk** [comment]
@dsabeti Hi, When i using single az
![image](https://user-images.githubusercontent.com/21106445/36274895-2d2f46c4-12c4-11e8-89fa-de84cc73125f.png)

my cloud-config is :
![image](https://user-images.githubusercontent.com/21106445/36274916-3e57f748-12c4-11e8-9ec7-8d6f02ed6217.png)

**Comment by dsabeti** [comment]
Hi @geekyzk. If you look at the [CPI configuration for vSphere](http://bosh.io/docs/vsphere-cpi.html#azs), you should see that the `clusters` section should include an array of maps rather than an array of strings. You probably want something like:
```
...
datacenters:
- name: DataCenter
  clusters:
  - { my_cluster: { resource_pool: my-vsphere-resource-pool }}
```

**Comment by geekyzk** [comment]
@dsabeti Thanks。I deploy success

**Comment by geekyzk** [comment]
Hi @dsabeti , I look [cf-deployment.yml](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml),For example:
```
uaa:
        sslCertificate: "((uaa_ssl.certificate))"
        sslPrivateKey: "((uaa_ssl.private_key))"
        zones:
          internal:
            hostnames:
            - uaa.service.cf.internal
```
What is the use of  uaa.service.cf.internal url ? I saw cf-release deployment.yml also has this url config(provide url),I don't know how to config the provide url,When I deploy cf-release, it will exception for connect uaa.service.cf.internal eg.. but in cf-deployment is not  thisexception.
