### ISSUE TITLE
App log is not displaying with cf logs 

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry/cf-deployment#411]
Hi,
We have deployed the CF using cf-deployment repo. All the VMs are in running state but the application logs is not displaying.

tried to get logs using:
cf logs APP_NAME
cf logs APP_NAME --recent

cf-deployment manifest version: v1.12.0
cloud: Alibaba

I have attached the screen shot.
![image](https://user-images.githubusercontent.com/25821409/36430399-1643fd14-167b-11e8-96d5-e11e37f4f41a.png)

**Comment by dsabeti** [comment]
Hi @lordcf. While you're running `cf logs`, can you also make an HTTP request (perhaps with `curl`) against the app? That should force some logs through.

I'm also going to loop in @xiaozhu36, who helps to support cf-deployment on Alibaba Cloud.

**Comment by lordcf** [comment]
Hi @dsabeti . I have curl the application after that too cf logs is not displaying anything.
The message will be like this only.

"Retrieving logs for app php-demo in org system / space testing as testuser...

**Comment by dsabeti** [comment]
@lordcf, ok. It looks like the traffic controller can't connect to the dopplers.  Can you check that there aren't any firewall rules blocking networking traffic between the two IP addresses?

Let's also get help from the Loggregator team: cc @ahevenor @JohannaSmith

**Comment by JohannaSmith** [comment]
@lordcf Those are pretty standard logs as the trafficcontroller continually reconnects to dopplers. Based on the time gap between the connection log and the gRPC context cancellation, I do believe trafficcontroller is discovering the doppler. 
I notice that it only connects to 1 doppler. How many doppler instances and trafficcontroller instances do you have? Because we would recommend at least 2 dopplers per AZ to increase log reliability/ chance of it getting through the system.

**Comment by lordcf** [comment]
@JohannaSmith  : Thanks for response.
We found the issue. Actually there is an metron_agent addons configure in the https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L10 files. But while deploying the cf. its not applying the by default to all vms (no metron_agent job running on the VMs).  We have created the new file with metron_agent.yml  which configuration is mention on cf-deployment.  After that I have done "update-runtime-config"  and then redeployed CF. 
Now metron_agent job is running on each VM and we are getting the logs.

But we have query, Why menton_agent addons is not applying while first time cf deployment?

**Comment by dsabeti** [comment]
@lordcf has the right question -- I'd expect the metron_agent addon to be added to each instance group. My guess is that you're using an older BOSH director that doesn't support deployment-level addons.

@lordcf, what version of the bosh director are you using? You can discover it by running `bosh env`.

**Comment by lordcf** [comment]
@dsabeti 
Bosh Version   264.7.0

**Comment by lordcf** [comment]
@dsabeti 
Bosh CLI: version 2.0.48

Please see the deployment command:

_bosh -e my-bosh -d cf deploy cf-deployment/cf-deployment.yml   --vars-store cf-vars.yml   -o cf-deployment/iaas-support/alicloud/stemcells.yml   -v region=eu-central-1   -v system_domain=$SYSTEM_DOMAIN   -v app_domains=$APP_DOMAIN_

**Comment by dsabeti** [comment]
This all makes it seem like it should work. The only thing that's unusual is that you're deploying to Alibaba cloud. Let's see if @xiaozhu36 can help out.

**Comment by xiaozhu36** [comment]
Hi @dsabeti I have no idea and I also happened this issue.

**Comment by dsabeti** [comment]
Ok @xiaozhu36. I want to make sure I understand what issue you're facing. You also see that the metron agent isn't colocated on all VMs? If so, then I think as the point of contact for Alibaba cloud, you should reach out to the BOSH team (cc @cppforlife @dpb587) to address the issue.

**Comment by jyriok** [comment]
Same for me here. 
i use cf-deployment 1.17-.1.18  on openstack.
Addons block doesn't works and  i don't have metron_agent on any vms..

bosh version 
```
bosh env
Using environment 'https://10.50.0.8:25555' as client 'bosh'

Name      my-bosh
UUID      f9500cb1-3610-4f94-a9fb-798932d9fc72
Version   261.4.0 (00000000)
CPI       openstack_cpi
Features  compiled_package_cache: disabled
          config_server: disabled
          dns: disabled
          snapshots: disabled
User      bosh

Succeeded
```
and bosh cli 

```
 bosh --version
version 2.0.45-d208799-2017-10-28T00:31:53
```

so i've make a ops file for add this on all vms (except smoke-tests)
```
# fix metron_agent addons


- type: replace
  path: /instance_groups/name=consul/jobs/name=metron_agent?
  value: &metron_agent-add
    name: metron_agent
    release: loggregator
    properties:
      loggregator:
        tls:
          ca_cert: "((loggregator_ca.certificate))"
          metron:
            cert: "((loggregator_tls_metron.certificate))"
            key: "((loggregator_tls_metron.private_key))"

- type: replace
  path: /instance_groups/name=router/jobs/name=metron_agent?
  value: *metron_agent-add

- type: replace
  path: /instance_groups/name=api/jobs/name=metron_agent?
  value: *metron_agent-add
etc.... 
```
