### ISSUE TITLE
How to set haproxy configration when deploy cf-deployment

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/cf-deployment#420]
Hi team:
   How to set haproxy configration when deploy cf-deployment.
   I use [use-haproxy](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-haproxy.yml) ops file,then it throw [haproxy_private_ip](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-haproxy.yml#L29) not set. When i add `-v haproxy_private_ip=192.168.7.100`  param,  it throw  `static ip192.168.7.100 which belongs to no subnet`, my cloud config:
```
networks:
- name: default
  subnets:
  - az: z1
    cloud_properties:
      name: Net_1007
    dns:
    - 192.168.7.1
    gateway: 192.168.7.254
    range: 192.168.7.0/24
    reserved:
    - 192.168.7.1
    - 192.168.7.2
    - 192.168.7.3
    - 192.168.7.4
    - 192.168.7.5
    - 192.168.7.6
    - 192.168.7.7
    - 192.168.7.8
    - 192.168.7.9
    - 192.168.7.10
    - 192.168.7.254
    - 192.168.7.255
```
Then i delete  [haproxy_private_ip](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-haproxy.yml#L29) line ,it deploy success,But when i use cli to login . it throw ` i/o timeout`。 

I found issues , see some people use this [ops file ](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/community/use-haproxy.yml).

Finally, How to config haproxy?
