### ISSUE TITLE
GCP - vm_extension - cf-route-network-properties

### ISSUE THREAD

**Issue by johnlonganecker** [cloudfoundry/cf-deployment#451]
We used bbl to create a bosh director on GCP and we are now trying to deploy CF on GCP but I am getting this error message:

```
Error: The vm_extension 'cf-router-network-properties' has not been configured in cloud-config
```

I am wondering what cloud properties I need to put in:

```
cf-router-network-properties
cf-tcp-router-network-properties
diego-ssh-proxy-network-properties
```

Some example cloud-config vm_extensions entries would be helpful :)

Thanks!

**Comment by dsabeti** [comment]
Hi @johnlonganecker. `bbl` should be setting up your bosh director with a good cloud-config automatically. What version of `bbl` are you using? Can you show your full `bbl up` command? Is there anything unusual about your `bbl-state` directory?

**Comment by johnlonganecker** [comment]
The cloud config was created with bbl but it was missing several things from the `vm_extensions` portion of the cloud config.

I added in these on vm_extensions: 

```
- name: cf-router-network-properties
- name: cf-tcp-router-network-properties
  cloud_properties:
    ports:
    - host: 1024-1123
- name: diego-ssh-proxy-network-properties
```

It got past that error, but not I need to increase my GCP Quota. I am going to assume this is resolved now.
