### ISSUE TITLE
Expose several CF properties as links?

### ISSUE THREAD

**Issue by menicosia** [cloudfoundry/cf-deployment#50]
We are producing a release which is meant to be deployed alongside CF. It's all BOSH-2.0-style work. Right now, to make this work, we need an Operator to copy and paste several values from the CF manifest to a variables file. To do this, we made a template with the following section:

```yaml
########################
# Cloud Foundry config #
########################

cf_api_url: https://api.bosh-lite.com
cf_uaa_admin_client_secret: admin-secret
cf_admin_username: admin
cf_admin_password: admin
cf_app_domains: [bosh-lite.com]
cf_sys_domain: bosh-lite.com
cf_skip_ssl_validation: true
cf_nats:
  machines: [10.244.0.6]
  user: nats
  password: nats
  port: 4222
```

As service authors, I don't think we should expect our Operator to copy and paste these values from their cf-manifest.

So this request, then is to please expose these features as links. I can understand the hesitation around some of them, especially UAA's admin password, but until [credhub](https://github.com/pivotal-cf/credhub-release) can be the solution to some of these issues, this is the best a service author has. After all, if the Operator already has access to all manifests, allowing these links isn't a significant additional exposure.
