### ISSUE TITLE
Experiment: cut off slow blob deletes in CC job, not Bits-Service

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/cf-deployment#678]
Hey guys,

Remember the CATs failing when Bits-Service was enabled in your GCP env (I believe trelawney)? It was due to hanging requests in GCP, which Bits-Service didn't cut off, which clogged CC workers, which prevented staging jobs to complete in time (to summarize the root cause in one sentence :-) ). As a solution we introduced a timeout in Bits-Service and it worked.

However, aborting these requests in Bits-Service is not necessarily the right solution, because ideally we'd like to let these requests succeed eventually (even if that means GCP returns from `DELETE` requests only after 6 (!) minutes).

To avoid clogging the CC workers despite slow `DELETE` requests, there is actually a property in CC, which I'd love to try out in your env. Concretely, this would mean, explicitly setting the following properties in the manifest:

```
instance_groups:
- name: bits
  jobs:
    - name: bits-service
      properties:
        bits-service:
          buildpacks:
            gcp_retry_timeout_seconds: 600
          droplets:
            gcp_retry_timeout_seconds: 600
          packages:
            gcp_retry_timeout_seconds: 600
          app_stash:
            gcp_retry_timeout_seconds: 600

- name: api
  jobs:
    - name: cloud_controller_ng
      properties:
        cc:
          jobs:
            blobstore_delete:
              timeout_in_seconds: 10

- name: cc-worker
  jobs:
    - name: cloud_controller_worker
      properties:
        cc:
          jobs:
            blobstore_delete:
              timeout_in_seconds: 10
```

In words this means: effectively do not cut off connections in Bits-Service, but cut off blobstore-delete jobs after 10s.

You'd have to run CATs multiple times to verify this works (as only one run might be green and only follow-up runs turn red).

Sorry, we would test this on our side, but as you know we cannot reproduce this problem in our envs.
Please let me know if you have more questions about how to set this up.

Thanks,
Peter

/cc @idev4u
