### ISSUE TITLE
[ENH] Request to use the certificate's CA

### ISSUE THREAD

**Issue by dirkjot** [cloudfoundry/cf-deployment#771]
### What is this issue about?

To use the cert rotation features provided by CredHub 2.3.0, the manifest should refer to the certificate's CA.  Currently, the manifest uses the CA's certificate.  

Example ` (( foobar_ca.certificate )) ` => ` (( foobar_certificate.ca )) `

_Steps_
N/A

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

cf-d 7.11.0 but this issue is present in all versions

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

PWS deploy, see https://github.com/pivotal-cloudops/pws-cf

### Please provide output that helps describe the issue:

See below for our ops file.

### What IaaS is this issue occurring on?

AWS

### Is there anything else unique or special about your setup?

Not really, just 1272 lines of organic, sustainable, hand-crafted yaml :-)

### Tag your pair, your PM, and/or team!

@shauravg @tjvman @dirkjot 

Ops file that we wrote for log_cache
```
+# NOTE:
+# Because cf-d uses ca.certificate instead of certificate.ca, we will fix it for
+# logcache here in oreder to do a ca rotation.
+# [#165477923]
+- type: replace
+  path: /instance_groups/name=doppler/jobs/name=log-cache/properties/tls/ca_cert
+  value: ((log_cache.ca))


```

Part of cf-deployment.yml that this modifies:
```
- name: doppler
  azs:
  - z1
  - z2
  instances: 4
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: doppler
    release: loggregator
    provides:
      doppler: {as: doppler, shared: true}
    properties:
      loggregator:
        tls:
          ca_cert: "((loggregator_ca.certificate))"
          doppler:
            cert: "((loggregator_tls_doppler.certificate))"
            key: "((loggregator_tls_doppler.private_key))"
  - name: log-cache
    provides:
      log-cache: {shared: true}
    properties:
      health_addr: localhost:6060
      tls:
        ca_cert: ((log_cache_ca.certificate))
        cert: ((log_cache.certificate))
        key: ((log_cache.private_key))
    release: log-cache
```
