### ISSUE TITLE
How can I deploy a non-web Python app in Cloud Foundry?

### ISSUE THREAD

**Issue by sresun** [cloudfoundry/cf-deployment#943]
Hello there! I have made a Python app that does nothing with the web.

Here is the content of the **manifest.yml**:

```
---
applications:
- name: my_app
  no-route: true
  health-check-type: process
  command: python daemon.py
  memory: 128M
  instances: 1
  timeout: 180
  buildpacks:
  - python_buildpack
  stacks: cflinuxfs3
```
  
and here is the content of the **Procfile**:
  
`web: python daemon.py`
  
 I have hosted it on Cloud Foundry but I think it is running as a web application. Because at the beginning of the **Log** of the app the first **Log** is this:

![Log](https://user-images.githubusercontent.com/63838516/140826323-e72bf2df-82cf-4771-af27-ab35eee97ef7.png)

and again in the Procfile, I have defined **web**

Can someone please tell me if my app is running as a non-web app or not? And if not then what do I have to do to make it work as a non-web app?

Thank you.
